import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const packageRoot = path.resolve(__dirname, '..');
const repoRoot = path.resolve(packageRoot, '../..');
const canonicalSchemaPath = path.resolve(repoRoot, 'schema/crp-v0.0.1.schema.json');
const canonicalExamplePath = path.resolve(
  repoRoot,
  'schema/examples/crp-v0.0.1.document.example.json',
);

const packageSchemaDir = path.resolve(packageRoot, 'schema');
const packageExampleDir = path.resolve(packageSchemaDir, 'examples');
const packageSchemaPath = path.resolve(packageSchemaDir, 'crp-v0.0.1.schema.json');
const packageExamplePath = path.resolve(packageExampleDir, 'crp-v0.0.1.document.example.json');
const generatedSchemaDir = path.resolve(packageRoot, 'src/generated');
const generatedSchemaPath = path.resolve(generatedSchemaDir, 'crp-v0.0.1.schema.ts');

function createGeneratedSchemaModule(schemaText) {
  const schema = JSON.parse(schemaText);
  const serialized = JSON.stringify(schema, null, 2);

  return `// This file is generated by scripts/sync-schema.mjs. Do not edit directly.
/* prettier-ignore */
export const CRP_V0_0_1_SCHEMA = ${serialized} as const;

export default CRP_V0_0_1_SCHEMA;
`;
}

async function run() {
  const checkOnly = process.argv.includes('--check');

  const [canonicalSchemaText, canonicalExampleText] = await Promise.all([
    readFile(canonicalSchemaPath, 'utf8'),
    readFile(canonicalExamplePath, 'utf8'),
  ]);
  const generatedSchemaText = createGeneratedSchemaModule(canonicalSchemaText);

  if (checkOnly) {
    const [existingSchemaText, existingExampleText, existingGeneratedText] = await Promise.all([
      readFile(packageSchemaPath, 'utf8').catch(() => null),
      readFile(packageExamplePath, 'utf8').catch(() => null),
      readFile(generatedSchemaPath, 'utf8').catch(() => null),
    ]);

    const outOfSync = [];
    if (existingSchemaText !== canonicalSchemaText) {
      outOfSync.push('schema/crp-v0.0.1.schema.json');
    }
    if (existingExampleText !== canonicalExampleText) {
      outOfSync.push('schema/examples/crp-v0.0.1.document.example.json');
    }
    if (existingGeneratedText !== generatedSchemaText) {
      outOfSync.push('src/generated/crp-v0.0.1.schema.ts');
    }

    if (outOfSync.length > 0) {
      console.error('Schema artifacts are out of sync:');
      for (const file of outOfSync) {
        console.error(` - ${file}`);
      }
      console.error('Run `pnpm --filter @cliproot/protocol schema:sync`.');
      process.exit(1);
    }

    return;
  }

  await Promise.all([mkdir(packageExampleDir, { recursive: true }), mkdir(generatedSchemaDir, { recursive: true })]);

  await Promise.all([
    writeFile(packageSchemaPath, canonicalSchemaText),
    writeFile(packageExamplePath, canonicalExampleText),
    writeFile(generatedSchemaPath, generatedSchemaText),
  ]);
}

run().catch((error) => {
  console.error(error);
  process.exit(1);
});
